# Generated by Django 5.2.5 on 2025-08-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_partyuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="partymember",
            unique_together={("name", "contact_number")},
        ),
        migrations.AlterField(
            model_name="partymember",
            name="contact_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="partymember",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.unit",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="partymember",
            name="previous_contact_number",
        ),
        migrations.RemoveField(
            model_name="partymember",
            name="previous_unit",
        ),
        migrations.RemoveField(
            model_name="partymember",
            name="user",
        ),
    ]
