# Generated by Django 5.2.5 on 2025-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_partymember_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partymember",
            name="unit",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
